### ISSUE TITLE
Jane Mapping problem

### ISSUE THREAD

**Issue by jwassermann** [krischer/jane#29]
While the mapping is correctly done within Jane, when requesting data via the fdsnws, the data come back with the original net,station,location,channel setting. This causes problems when the stationxml is containing the mapped names (which only make sense).

**Comment by krischer** [comment]
Thanks for the fix! Looks good.

@jwassermann : The dataselect query currently (and also before this fix) does not serve the original MiniSEED files and some blockettes might be lost - also the records are repacked. This is because they are read into ObsPy once and then sent over HTTP. There are certain blockettes ObsPy does not preserve. Is this something we should look into for the long run or does it not matter?

The fdsn-ws standard does not really clarify how to best handle this, especially if the requested start- + end time do not exactly coincide with a record boundary.

**Comment by megies** [comment]
> @jwassermann : The dataselect query currently (and also before this fix) does not serve the original MiniSEED files and some blockettes might be lost - also the records are repacked. This is because they are read into ObsPy once and then sent over HTTP. There are certain blockettes ObsPy does not preserve. Is this something we should look into for the long run or does it not matter?

I think it's fine. Most of the time you don't care about those low-level details, and if you do, there's still still original files that can be looked up if necessary.
